Repository Skyscanner/stylelint-config-skyscanner, pull requests merged in 2023-07, with the labels that each got.

#291 Adding automation to release s-c-s
  .github/release-drafter.yml
  .github/workflows/_test.yml
  .github/workflows/ci.yml
  .github/workflows/label-check.yml
  .github/workflows/main.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
Labels: skip-changelog

#293 [KOA-6224] Update to Stylelint v15 and Prettier v3
  CHANGELOG.md
  UNRELEASED.md
  docs/release.md
  index.js
  index.test.js
  package-lock.json
  package.json
Labels: major

#295 [KOA-6224] Adjust non-compatible rules
  index.js
Labels: minor
